import inspect
from sciunit.capabilities import Runnable
from neurounit.capabilities import ProducesMembranePotential,ProducesSpikes
from neurounit.capabilities import ReceivesCurrent,spike_functions
from neurounit import neuroelectro
from sciunit.tests import StandardTest
from sciunit.comparators import ZComparator # Comparators.  
from sciunit.comparators import ZScoreToBooleanScore # Converters.  
from sciunit.scores import BooleanScore # Scores.  
try:
	import numpy as np
except:
	print "NumPy not loaded."

class ZTest(StandardTest):
	"""A Z-score test."""
	
	def __init__(self,
			     reference_data={},
			     model_args={},
			     threshold=2):
		print "Instantiating a test of %s" % self.desc
		StandardTest.__init__(self,reference_data,model_args,ZComparator)
		self.conversion_params = {'thresh':threshold}
		"""-2 < Z-score < 2 required to get a BooleanScore of True, 
		i.e. to pass the test."""
 
	comparator = ZComparator
	"""Compare the model to the reference and generate a Z-score."""

	converter = ZScoreToBooleanScore
	"""Convert from Z-score (generated by ZComparator) to Boolean score."""  


class SpikeWidthTest(ZTest):
	"""Tests the full widths of spikes at their half-maximum."""
	
	def __init__(self,
			     reference_data={'mean':None,'std':None},
			     model_args={}):
		"""Takes the mean and standard deviation of reference spike widths"""
		print "Instantiating a spike width test."
		ZTest.__init__(self,reference_data,model_args) 
		"""Register reference data and model arguments."""  
		self.required_capabilities += (ProducesMembranePotential,
							  		   ProducesSpikes,)

	desc = "spike widths"

	def get_model_data(self,model):
		"""Extracts data from the model and returns it."""
		spikes = model.get_spikes() # Method implementation guaranteed by 
									# ProducesSpikes capability. 
		widths = spike_functions.spikes2widths(spikes)
		widths *= 1000 # Convert from s to ms.  
		model_data = {'mean':mean(widths),
					  	'std':std(widths)}
		return model_data

	def get_model_stats(self,model_data):
		"""Puts model stats in a form that the Comparator will understand."""
		return {'value':model_data['mean']}
		
	#def get_reference_stats(self):
	#	"""Puts reference stats in a form that the Comparator will understand."""
	#	return {'mean':self.reference_data['mean'],
	#			'std':self.reference_data['std']}
		
	#def generate_score(self,model_data):
	#	"""Return a score for the model on this test."""  
	#	score = super(SpikeWidthTest,self).generate_score(model_data)
	#	return score


class SpikeWidthTestDynamic(SpikeWidthTest):
	"""Tests the full widths of spikes at their half-maximum under current injection."""

	def __init__(self,
				 reference_data=SpikeWidthTest.__init__.im_func.func_defaults[0],  
			     model_args={'injected_current':0.0}):
		"""Takes a steady-state current to be injected into a cell."""

		SpikeWidthTest.__init__(self,reference_data,model_args) 
		self.required_capabilities += (ReceivesCurrent,)

	desc = "spike widths under current injection"


class RestingPotentialTest(ZTest):
	"""Tests the resting potential under zero current injection."""
	
	def __init__(self,
			     reference_data={'mean':None,'std':None},
			     model_args={}):
		"""Takes the mean and standard deviation of reference spike widths"""
		
		ZTest.__init__(self,reference_data,model_args) 
		"""Register reference data and model arguments."""  
		
		self.required_capabilities += (ProducesMembranePotential,
							  		   ReceivesCurrent,)

	desc = "resting potential (zero current injection)"

	def run_test(self,model,**kwargs):
		current_ampl = 0.0
		model.set_current_ampl(current_ampl) 
		print "Setting current amplitude to %f" % current_ampl
		# Setting injected current to zero.  
		score = super(RestingPotentialTest,self).run_test(model,**kwargs) # Run the model.  
		score.related_data = model.get_membrane_potential()
		return score

	def get_model_data(self,model):
		"""Extracts data from the model and returns it."""
		
		resting_potential = model.get_median_vm() # Resting potential in mV.
		model_data = {'value':resting_potential,}
		return model_data
		
		