COMMENT

   **************************************************
   File generated by: neuroConstruct v1.5.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   K_AHP (Type: Channel mechanism, Model: ChannelML based process)

   with parameters: 
   /channelml/@units = SI Units 
   /channelml/notes = A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a     Detailed Network Model of the Cerebellar Granule  ... 
   /channelml/channel_type/@name = K_AHP 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = k 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 20 
   /channelml/channel_type/current_voltage_relation/@default_erev = -0.08 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@name = Calcium 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@ion = ca 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@charge = 2 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@variable_name = conc 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@min_conc = 0 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@max_conc = 1000 
   /channelml/channel_type/current_voltage_relation/gate/@name = m 
   /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = m0 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@id = m 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@name = alpha 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@from = m0 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@to = m 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr = conc &lt; 500 ? 0.02*conc : 10.0 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@name = beta 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@from = m 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@to = m0 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr = conc &lt; 500 ? -0.02*conc + 1.0 : -9.0 
   /channelml/channel_type/impl_prefs/table_settings/@max_v = 0.05 
   /channelml/channel_type/impl_prefs/table_settings/@min_v = -0.1 
   /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 300 

// File from which this was generated: /home/kali/nC_projects/CA1_NEURON/cellMechanisms/K_AHP/K_AHP.xml

// XSL file with mapping to simulator: /home/kali/nC_projects/CA1_NEURON/cellMechanisms/K_AHP/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: SI Units

COMMENT
    A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a
    Detailed Network Model of the Cerebellar Granule Cell Layer
ENDCOMMENT

TITLE Channel: K_AHP

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX K_AHP3
    USEION k READ ek WRITE ik VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    USEION ca READ cai VALENCE 2 ? internal concentration of ion is read

    
    RANGE gmax, gion
    
    RANGE minf, mtau
    
}

PARAMETER { 
      

    gmax = 0.0020 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
          

    ? The internal concentration of ion: ca is used in the rate equations...
    cai (mM)   
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    
}

BREAKPOINT { SOLVE states METHOD derivimplicit     

    gion = gmax*((1*m)^1)      

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -80
        
    settables(v,cai)
    m = minf
        
    
}
    
STATE {
    m
    
}

DERIVATIVE states {
    settables(v,cai)
    m' = (minf - m)/mtau
    
}

PROCEDURE settables(v(mV), cai(mM)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, conc, temp_adj_m, A_alpha_m, B_alpha_m, Vhalf_alpha_m, A_beta_m, B_beta_m, Vhalf_beta_m
    
    
    UNITSOFF
    temp_adj_m = 1
    
    ? Gate depends on the concentration of ca
    conc = cai ? In NEURON, the variable for the concentration  of ca is cai
    
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
         
    ? Found a generic form of the rate equation for alpha, using expression: conc < 500 ? 0.02*conc : 10.0
    
    ? Note: Equation (and all ChannelML file values) in SI Units so need to convert v first...
    
    v = v * 0.0010   ? temporarily set v to units of equation...
            
    
    
    if (conc < 50 ) {
        alpha =  0.2*conc 
    } else {
        alpha =  10.0
    }
    ? Set correct units of alpha for NEURON
    alpha = alpha * 0.0010 
    
    beta =  1.0

    ? Set correct units of beta for NEURON
    beta = beta * 0.0010 
    
    v = v * 1000   ? reset v
        
    mtau = 1/(temp_adj_m*(alpha + beta))
    minf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: m ***
    

         

}


UNITSON


